language: objective-c

branches:
 only:
 - master

xcode_project: Patchwire-iOS.xcodeproj
xcode_scheme: Patchwire-iOS
osx_image: xcode7.3
xcode_sdk: iphonesimulator9.3

before_install:
 - brew update
 - brew upgrade xctool
