language: objective-c

branches:
 only:
 - master

xcode_project: Patchwire-iOS.xcodeproj
xcode_scheme: Patchwire-iOS
osx_image: xcode6.3
xcode_sdk: iphonesimulator8.3

script:
- xcodebuild clean build test -project Patchwire-iOS.xcodeproj -scheme Patchwire-iOS
