language: objective-c

branches:
 only:
 - master

xcode_project: Patchwire-iOS.xcodeproj
xcode_scheme: Patchwire-iOS
osx_image: xcode8.3
xcode_sdk: iphonesimulator10.3

before_install:
  - sudo gem install xcpretty

script:
  - xcodebuild -project Patchwire-iOS.xcodeproj/ -scheme 'Patchwire-iOS' -destination 'platform=iOS Simulator,name=iPhone 6,OS=10.3' clean build test | xcpretty && exit ${PIPESTATUS[0]}
