language: objective-c

branches:
 only:
 - master

xcode_project: Patchwire-iOS.xcodeproj
xcode_scheme: Patchwire-iOS
osx_image: xcode7.3
xcode_sdk: iphonesimulator9.3

script:
  xcodebuild -project Patchwire-iOS.xcodeproj -scheme Patchwire-iOS -sdk iphonesimulator9.3 build test
