language: objective-c

branches:
 only:
 - master

xcode_project: Patchwire-iOS.xcodeproj
xcode_scheme: Patchwire-iOS
osx_image: xcode7.3
xcode_sdk: iphonesimulator9.3

before_install:
  - sudo gem install xcpretty
  - SIMULATOR_ID=$(xcrun instruments -s | grep -o "iPhone 6 (9.3) \[.*\]" | grep -o "\[.*\]" | sed "s/^\[\(.*\)\]$/\1/")

script:
  - open -a "simulator" --args -CurrentDeviceUDID $SIMULATOR_ID
  - xcodebuild -project Patchwire-iOS.xcodeproj/ -scheme 'Patchwire-iOS' -destination 'platform=iOS Simulator,name=iPhone 6,OS=9.3' clean build | xcpretty
  - xcodebuild -project Patchwire-iOS.xcodeproj/ -scheme 'Patchwire-iOS' -destination 'platform=iOS Simulator,name=iPhone 6,OS=9.3' test | xcpretty
