language: objective-c

branches:
 only:
 - master

xcode_project: Patchwire-iOS.xcodeproj
xcode_scheme: Patchwire-iOS
osx_image: xcode7.3
xcode_sdk: iphonesimulator9.3

before_install:
  - sudo gem install xcpretty

script:
  - xcodebuild -project Patchwire-iOS.xcodeproj/ -scheme 'Patchwire-iOS' -destination 'platform=iOS Simulator,name=iPhone 6,OS=9.3' clean build | xcpretty && exit ${PIPESTATUS[0]}
  - xcodebuild -project Patchwire-iOS.xcodeproj/ -scheme 'Patchwire-iOS' -destination 'platform=iOS Simulator,name=iPhone 6,OS=9.3' test | xcpretty && exit ${PIPESTATUS[0]}
